# Generated by Django 4.2.7 on 2025-10-30 11:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandSnippet",
            fields=[],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.brand",),
        ),
        migrations.CreateModel(
            name="CategorySnippet",
            fields=[],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.category",),
        ),
        migrations.AlterField(
            model_name="product",
            name="compare_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price for showing discounts",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Extra price for this variant",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="variant",
            name="product",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="products.product",
            ),
        ),
    ]
